import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { texts } from "@/styles/texts";

import { useEffect } from "react";

import { Space_Grotesk } from "@next/font/google";

import { youtube, soundcloud, beatstars, beats, server} from "@/config";

import bg from "../public/bg.png";
import filter from "../public/filter.svg";
import right from "../public/right.svg";

const space_grotesk = Space_Grotesk({ subsets: ["latin"], weight: "700"});

export default function Home() {
	useEffect(() => {
        window.addEventListener("scroll", event => {
			const navItems = Array.from(document.getElementsByClassName("nav-item"));

			if (document.getElementsByTagName("html")[0].getAttribute("selected") != "") {
				if(document.getElementsByTagName("main")[0].getBoundingClientRect().top > -42) {
					document.getElementById("header").classList.remove("border-b", "border-black", "bg-black/25", "backdrop-blur-xl");
					document.getElementById("search-bar").classList.remove("translate-y-1/2", "bg-white/20");
					document.getElementById("search-bar").classList.add("bg-white/10");

					navItems.forEach(element => {
						element.classList.remove("translate-y-1/4");
					});
				} else {
					document.getElementById("header").classList.add("border-b", "border-black", "bg-black/25", "backdrop-blur-xl");
					document.getElementById("search-bar").classList.add("translate-y-1/2");
					document.getElementById("search-bar").classList.remove("bg-white/10");
					document.getElementById("search-bar").classList.add("bg-white/20");

					navItems.forEach(element => {
						element.classList.add("translate-y-1/4");
					});
				}
			}
		});
	}, []);
	
	return (
		<>
			<Head>
				<title>Jakimixedit</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-cover bg-fixed min-h-screen"
			style={{
				backgroundImage: `url(${bg.src})`,
			}}>
				<nav id="header" className="flex flex-row items-top justify-between w-full p-8 pt-4 pb-4 gap-8 fixed top-0 left-0 z-50">
					<h1 className={space_grotesk.className + " " + texts.title}>
						Jaki<span className={"a -ml-4 italic tracking-tighter text-white/50 inline-block"}>mixed</span>it
					</h1>
					<h1 className={space_grotesk.className + " text-xl transition-all nav-item"}>
						<Link href={ youtube } className="hover:text-red-600 transition-colors">youtube</Link>
					</h1>
					<h1 className={space_grotesk.className + " text-xl transition-all nav-item"}>
						<Link href={ soundcloud } className="hover:text-yellow-600 transition-colors">soundcloud</Link>
					</h1>
					<h1 className={space_grotesk.className + " text-xl transition-all nav-item"}>
						<Link href={ beatstars } className="hover:text-red-600 transition-colors">beatstars</Link>
					</h1>
					<div id="search-bar" className={space_grotesk.className + " flex justify-center items-center gap-4 rounded-full border border-white h-8 px-4 bg-white/10 text-white/25 hover:text-white backdrop-blur-3xl transition-all"} >Search for beats...<Image alt="Filter" className="p-1" src={filter}></Image></div>
				</nav>
				<div className="flex justify-center self-center pt-24">
					<div className="flex flex-wrap p-8 gap-8">
						<div>
							<h2 className={space_grotesk.className + " text-2xl px-4"}>Latest Drop</h2>
							<div className="rounded-2xl bg-white/10 flex md:flex-row flex-col max-w-2xl">
								<div className="h-96 w-96 bg-white/10 rounded-2xl"></div>
									<div className="flex-row p-6 md:p-8">
										<p className={space_grotesk.className + " md:pt-0 pt-2 text-sm opacity-60"}>2023/01/11</p>
										<div className="flex gap-4 items-baseline">
											<p className={space_grotesk.className + " text-3xl"}>hearthless</p>
											<p className={space_grotesk.className + " text-base opacity-50"}>1:14</p>
										</div>
										<div className="flex gap-8 pt-4">
											<p className={space_grotesk.className}><span className="text-2xl">140</span><span className="opacity-60">bpm</span></p>
											<p className={space_grotesk.className}><span className="text-2xl">C</span><span className="opacity-60"> sharp minor</span></p>
										</div>
										<p className={space_grotesk.className + " opacity-60 text-justify"}>lunchbox x cheromani x new jazz ype beat</p>
										<div className="flex gap-4">
													<p className={space_grotesk.className + " pt-4 text-violet-600"}>#cheromani</p>
													<p className={space_grotesk.className + " pt-4 text-fuchsia-600"}>#newjazz</p>
													<p className={space_grotesk.className + " pt-4 text-amber-600"}>#hardrock</p>
												</div>
											<Link href={ server + "/beats/hearthless" } className={space_grotesk.className + " text-right pt-12 text-2xl flex justify-end items-center"}>More<Image alt="More" className="p-1 w-12 h-12" src={right}></Image></Link>
									</div>
								</div>
							</div>
							<div>
								<h2 className={space_grotesk.className + " text-2xl px-4"}>Most Popular</h2>
								<div className="rounded-2xl bg-white/10 flex md:flex-row flex-col max-w-2xl">
									<div className="h-96 w-96 min-h-fit min-w-fit bg-white/10 rounded-2xl"></div>
										<div className="flex flex-col justify-between p-6 md:p-8">
											<div className="flex flex-col">
												<p className={space_grotesk.className + " md:pt-0 pt-2 text-sm opacity-60"}>11.421 streams</p>
												<div className="flex gap-4 items-baseline">
													<p className={space_grotesk.className + " text-3xl"}>plot!</p>
													<p className={space_grotesk.className + " text-base opacity-50"}>2:03</p>
												</div>
												<div className="flex gap-8 pt-4">
													<p className={space_grotesk.className}><span className="text-2xl">142</span><span className="opacity-60">bpm</span></p>
													<p className={space_grotesk.className}><span className="text-2xl">F</span><span className="opacity-60"> major</span></p>
												</div>
												<p className={space_grotesk.className + " opacity-60 text-justify"}>lunchbox x cheromani x new jazz ype beat</p>
												<div className="flex gap-4">
													<p className={space_grotesk.className + " pt-4 text-violet-600 hover:text-violet-400 transition-colors"}>#iayze</p>
													<p className={space_grotesk.className + " pt-4 text-fuchsia-600 hover:text-fuchsia-400 transition-colors"}>#domcorleo</p>
													<p className={space_grotesk.className + " pt-4 text-amber-600 hover:text-amber-400 transition-colors"}>#hardrock</p>
												</div>
											</div>
											<Link href={ server + "/beats/plot" } className={space_grotesk.className + " text-right pt-12 text-2xl flex justify-end items-center"}>More<Image alt="More" className="p-1 w-12 h-12" src={right}></Image></Link>
										</div>
									</div>
							</div>
						<div>
						<h2 className={space_grotesk.className + " text-2xl px-4"}>All Beats <span className="text-sm opacity-60">({beats.length})</span></h2>
							<div className="flex flex-wrap gap-2">
								{ beats.map((beat) => {
									let name = (beat.name.substring(0, 16));
									if (beat.name !== name) {
										name += "...";
									}

									return (
										<Link key={beat.cover} href={ encodeURI(server + "/beats/" + beat.name) } className="flex flex-col justify-center items-center content-center group">
											<div className="a h-32 w-32 bg-white/20 rounded-2xl"></div>
											<span className={space_grotesk.className + " text-base transition-colors text-white/60 group-hover:text-white"}>{ name }</span>
										</Link>
									)
								}) }
							</div>
						</div>
					</div>
				</div>
				<footer className="flex flex-row items-top justify-between items-center w-full p-8 pt-4 pb-4 gap-8 z-50 border-t border-black bg-black/25 backdrop-blur-xl">
					<div className="flex flex-row items-top justify-start items-center gap-2">
						<div className={ space_grotesk.className + " text-base text-white/60"}>Made by <Link href="https://www.kekesi.dev" className="text-white">Kristof Kekesi</Link> for</div>
						<h1 className={space_grotesk.className + " text-2xl"}>
							Jaki<span className={"a -ml-1 italic tracking-tighter text-white/50 inline-block"}>mixed</span>it
						</h1>
					</div>
					<div className={ space_grotesk.className + " text-base text-white/60"}>Copyright © 2023 Jakimixedit. All Rights Reserved.</div>
				</footer>
			</main>
		</>
	)
}
